spring:
    flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration
    # Data source properties
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        show-sql: true
#    sql:
#        init:
#            mode: always
    datasource:
        url: jdbc:mysql://mysql:3306/numbers?createDatabaseIfNotExist=true
        schema: public
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always
#    datasource:
#        url: jdbc:h2:mem:mydb
#        username: sa
#        password: password
#        driverClassName: org.h2.Driver
#    jpa:
#        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    # Rabbit Message Queue properties
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: guest
        password: guest

# Scheduler properties
scheduler:
    # initial delay in milliseconds
    delay: 0
    # interval in milliseconds
    interval: 10000

queue:
    name: my-queue
    exchange: code-challenge
    routing-key: numbers

# Logging properties
logging:
    level:
        root: INFO